# Generated by Django 4.2.2 on 2025-06-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_auto_20250528_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='talents/'),
        ),
    ]
